### ISSUE TITLE
build and deploy

### ISSUE THREAD

**Issue by robdove** [robmellett/shopify-tailwind-vue#1]
Firstly thanks for being the only reference of shopify and tailwind on the internet!

How are you building this to deploy? I can get it working locally when developing but when I run yarn deploy tailwind doesn't compile.

**Comment by robmellett** [comment]
Hey @robdove,

Apologies about getting back to you so late, I must have missed this notification.

The project uses Shopify Slate under the hood, so you can start the project with `yarn start`, and for deploying the site to shopify you can use `yarn deploy`

Just remember to create a .`env` from `.env-sample` with your shopify settings.

PostCSS should already be configured, you can see the available options under `slate.config.json`

Hope this helps
